<?php
define('MESSAGE_SUCCESS', 0);
define('MESSAGE_ERROR', 1);
define('MESSAGE_ERROR_NOTFOUND', 2);
define('MESSAGE_ERROR_NOTSIGNED', 3);
define('MESSAGE_ERROR_GOLD_NOTENOUGH', 4);
define('MESSAGE_ERROR_CRYSTAL_NOTENOUGH', 5);
define('MESSAGE_ERROR_GOLD_NOTABLE', 6);
define('MESSAGE_ERROR_CRYSTAL_NOTABLE', 7);
?>